name: test
recipe: laravel
config:
  webroot: public
  cache: redis

services:
  node-service:
    type: php
    build_as_root:
      # Note that you will want to use the script for the major version of node you want to install
      # See: https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions
      - curl -sL https://deb.nodesource.com/setup_20.x | bash -
      - apt-get install -y nodejs
tooling:
  node:
    service: node-service
  npm:
    service: node-service
  npx:
    service: node-service
